sonar.projectKey=mrsahiljaiswal_devops
sonar.organization=mrsahiljaiswal

sonar.projectName=DevopsLab
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.host.url=https://sonarcloud.io
sonar.token=7f091305afaba31fc6ec001fc51adf5e818c73db

sonar.exclusions=node_modules/**,public/**,api/**,Dockerfile,Jenkinsfile,**/*.md,**/*.sh